### ISSUE TITLE
An erro in Super_resolution

### ISSUE THREAD

**Issue by Zack-Tsang** [gpleiss/ciq_experiments#1]
Hello, I think your work interesting, but when I reproduced your work, I met an error when ran 'sr.py', it threw an error: "AttributeError: module 'gpytorch.settings' has no attribute 'record_ciq_stats'". I search the document about gpytorch1.3, and it does have the 'record_ciq_stats' function in 'gpytorch.settings'. So, could you tell me how to fix it? Thank you very much!

**Comment by gpleiss** [comment]
That was a leftover line from a development branch of gpytorch. `sr.py` should be fixed now.

**Comment by Zack-Tsang** [comment]
Hi, Dr. Geoff Pleiss,

I test the new code, it works well! Thank you very much!

 Best regards,
 Zhiyong Tsang
